# Service configuration for AccountService
---
service_name: account-service
#grpc_hostname: acctsvc
grpc_hostname: localhost
grpc_port: 50051
hz_mode: embedded
# client config only used when hz_mode is client-server
#hz_client_config: hazelcast-client.hzce.yaml